version: '3.8'

services:
  gazebo:
    build:
      context: .
      dockerfile: Dockerfile.gazebo
    container_name: gazebo-vnc
    ports:
      - "8080:8080"  # NoVNC web interface
      - "5901:5901"  # VNC port
    volumes:
      # Mount local directory for custom Gazebo worlds and models
      - ./gazebo_data/models:/gazebo_workspace/models
      - ./gazebo_data/worlds:/gazebo_workspace/worlds
      # Persist VNC configuration
      - vnc_data:/root/.vnc
    environment:
      - DISPLAY=:1
      - VNC_RESOLUTION=1024x768
      - VNC_DEPTH=24
      - VNC_PASSWORD=gazebo
      - GAZEBO_MODEL_PATH=/gazebo_workspace/models:/usr/share/gazebo-11/models
    restart: unless-stopped
    # Enable shared memory for GUI applications
    shm_size: '2gb'
    # Add capabilities for GUI applications
    cap_add:
      - SYS_PTRACE
    # Optional: Enable GPU acceleration if nvidia-docker is available
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all

volumes:
  vnc_data:
    driver: local