# Generated by Django 5.2.4 on 2025-07-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_image_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('contact', 'Contact Form'), ('meeting', 'Meeting Scheduling Form'), ('home', 'Home Page Contact Form')], help_text='Type of form submitted', max_length=20)),
                ('name', models.CharField(help_text='Full name of the submitter', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the submitter', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Message or additional notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the form was submitted')),
                ('subject', models.CharField(blank=True, help_text='Subject line (for contact forms)', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Phone number (for meeting forms)', max_length=20)),
                ('meeting_purpose', models.CharField(blank=True, choices=[('buy_kit', 'Buy Robotics Kit'), ('custom_project', 'Discuss Custom Project')], help_text='Purpose of the meeting', max_length=20)),
                ('preferred_date', models.CharField(blank=True, help_text='Preferred meeting date', max_length=50)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
